export const STRINGS = {
    common: {
        appName: 'Hostlify',
        smartManagement: 'Smart Hostel Management',
        submit: 'Submit',
        cancel: 'Cancel',
        save: 'Save',
        edit: 'Edit',
        delete: 'Delete',
        back: 'Back',
        continue: 'Continue',
        loading: 'Loading...',
        noData: 'No data available',
        required: '*',
        allFieldsRequired: 'All fields marked * are required',
    },
    auth: {
        hostellerPortal: 'Hosteller Portal',
        staffPortal: 'Staff Portal',
        superAdminPortal: 'Super Admin Portal',
        signIn: 'Sign In',
        signUp: 'Sign Up',
        emailPlaceholder: 'yourname@email.com',
        password: 'Password',
        passwordPlaceholder: '••••••••',
        forgotPassword: 'Forgot password?',
        newResident: 'New resident?',
        registerQR: 'Register with hostel QR code',
        isStaff: 'Are you hostel staff?',
        staffLoginLink: 'Staff Login →',
        isHosteller: 'Are you a resident?',
        hostellerLoginLink: 'Hosteller Login →',
        createAccount: 'Create your account',
        firstName: 'First Name',
        lastName: 'Last Name',
        email: 'Email Address',
        mobile: 'Mobile Number',
        gender: 'Gender',
        dob: 'Date of Birth',
        registrationStep1: 'Step 1 — Personal Information',
        registrationStep2: 'Step 2 — Address',
        registrationStep3: 'Step 3 — Emergency',
        registrationStep4: 'Step 4 — Review',
    },
    portal: {
        dashboard: 'Dashboard',
        myDues: 'My Dues',
        myProfile: 'My Profile',
        complaints: 'Complaints',
        menu: 'Menu',
        leave: 'Leave',
        service: 'Service',
        referral: 'Referral',
        announcements: 'Announcements',
        members: 'Members',
        payments: 'Payments',
        expenses: 'Expenses',
        allocations: 'Pending Allocations',
    }
}
